excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - iOSTests
  - iOSUITests
  - fastlane
disabled_rules: 
  - line_length
  - identifier_name
  - force_try # try! Realm()
  - force_cast # static func createWith()  -> as? ViewController
  - todo
  - trailing_comma