# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'


target 'Animusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase
  pod 'Firebase/Firestore'

  # Reactive
  pod 'RxSwift', '~> 5.1.0'
  pod 'RxCocoa', '~> 5.1.0'
  pod 'RxRealm'
  pod 'RxDataSources', '~> 4.0'
  
  # Networking
  pod 'Kingfisher'

  # Realm
  pod 'RealmSwift'
  
  # Tools
  pod 'SwiftLint'
  pod 'Then'

  target 'AnimusicTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

  target 'AnimusicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
